// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.io.org.visualx.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;


/**
 * 
 * Characteristic of an item in a category. For example, "Shoes Size" or "Style"
 * might be aspects of the Men's Shoes category, while "Genre" and "Album Type"
 * could be aspects of the Music CDs category.
 * <br><br>
 * This container is not returned if there are no matching aspects for thecategory.
 * 
 */
public class Aspect implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element    
	@Order(value=0)
	public List<AspectValueHistogram> valueHistogram;	
	
	@Element    
	@Order(value=1)
	public String delimiter;	
	
	@AnyElement
	@Order(value=2)
	public List<Object> any;	
	
	@Attribute  
	@Order(value=3)
	public String name;	
	
    
}