// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.io.org.visualx.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;


/**
 * 
 * <b>As of October 2014, domains will be deprecated and "category" is used instead. </b>
 * 
 */
public class DomainFilter implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element    
	@Order(value=0)
	public List<String> domainName;	
	
	@Element    
	@Order(value=1)
	public String delimiter;	
	
	@AnyElement
	@Order(value=2)
	public List<Object> any;	
	
    
}