// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.io.org.visualx.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;


/**
 * 
 * Returns items based on a product base on ISBN, UPC, EAN, or ePID (eBay Product Reference
 * ID).
 * 
 */
@com.leansoft.nano.annotation.RootElement(name = "findItemsByProductRequest", namespace = "http://www.ebay.com/marketplace/search/v1/services")
public class FindItemsByProductRequest extends BaseFindingServiceRequest implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element    
	@Order(value=0)
	public ProductId productId;	
	
	@Element    
	@Order(value=1)
	public List<ItemFilter> itemFilter;	
	
	@Element    
	@Order(value=2)
	public List<OutputSelectorType> outputSelector;	
	
    
}