// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.io.org.visualx.ebay.marketplace.search.v1.services;

import java.io.Serializable;


/**
 * 
 * Response container for the getVersion call.
 * 
 */
@com.leansoft.nano.annotation.RootElement(name = "getVersionResponse", namespace = "http://www.ebay.com/marketplace/search/v1/services")
public class GetVersionResponse extends BaseServiceResponse implements Serializable {

    private static final long serialVersionUID = -1L;

    
}